name: Build QF Solochain (Debug)

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Debug Build
    runs-on: self-hosted
    labels:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install -y gcc g++ make curl git protobuf-compiler libclang-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup target add wasm32-unknown-unknown --toolchain nightly-aarch64-unknown-linux-gnu
          export PATH="$HOME/.cargo/bin:$PATH"
          echo $PATH

      - name: Create test files
        run: |
          mkdir qf-solochain
          cd qf-solochain
          mkdir output
          cd output
          echo "test" > test
          echo "test.wasm" > test.wasm

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: qf-solochain/output/
