name: Build and Release QF Solochain

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup build environment
        run: |
          sudo apt update
          sudo apt install -y gcc g++ make curl git protobuf-compiler libclang-dev
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
          export PATH="$HOME/.cargo/bin:$PATH"
          rustup target add wasm32-unknown-unknown --toolchain nightly-x86_64-unknown-linux-gnu
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Build Project
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          make vendor-clone
          make qf-node

      - name: Generate release name
        id: release_name
        run: |
          REPO_NAME=$(basename $(git rev-parse --show-toplevel))
          DATE=$(date +'%d.%m.%Y')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "RELEASE_NAME=${REPO_NAME}-${DATE}-${COMMIT_HASH}" >> $GITHUB_ENV
          echo "TAG_NAME=${DATE}-${COMMIT_HASH}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          body: |
            **Release Notes**
            - Placeholder for changes in this release.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
